version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - lnd_0_rpc:/lnd_0_rpc
      - lnd_1_rpc:/lnd_1_rpc
    ports:
      - "3000:3000"
    depends_on:
      - db

  btcd:
    image: btcd
    build:
      context: docker/btcd/
    volumes:
      - btcd_rpc:/rpc
      - blockchain:/data
    environment:
      MINING_ADDRESS:
      NETWORK: simnet
      RPCUSER: devuser
      RPCPASS: devpass
    command: ./start-btcd.sh --simnet --datadir=/data

  lnd_0:
    hostname: lnd_0
    build:
      context: docker/lnd/
    volumes:
      - btcd_rpc:/rpc
      - lnd_0:/root/.lnd/
    environment:
      NETWORK: simnet
      DEBUG: debug
      RPCUSER: devuser
      RPCPASS: devpass
    depends_on:
      - btcd

  lnd_1:
    hostname: lnd_1
    build:
      context: docker/lnd/
    volumes:
      - btcd_rpc:/rpc
      - lnd_1:/root/.lnd/
    environment:
      NETWORK: simnet
      DEBUG: debug
      RPCUSER: devuser
      RPCPASS: devpass
    depends_on:
      - btcd

volumes:
  btcd_rpc:
    driver: local

  lnd_0:
    driver: local

  lnd_1:
    driver: local

  blockchain:
    driver: local
