kind: Service
apiVersion: v1
metadata:
  name: btcd
  labels:
    app: btcd
spec:
  type: LoadBalancer
  selector:
    app: btcd
  ports:
  - name: wire
    protocol: TCP
    port: 18333
    targetPort: 18333
  - name: rpc
    protocol: TCP
    port: 18334
    targetPort: 18334
