kind: Service
apiVersion: v1
metadata:
  name: lnd
  labels:
    app: lnd
spec:
  type: LoadBalancer
  selector:
    app: lnd
  ports:
  - name: peer
    protocol: TCP
    port: 9735
    targetPort: 9735
  - name: rpc
    protocol: TCP
    port: 10009
    targetPort: 10009
