apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lnd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lnd
    spec:
      containers:
      - name: lnd
        image: gcr.io/uiu-server/lnd
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: 50m

        env:
          - name: RPCUSER
            valueFrom:
              secretKeyRef:
                name: btcd-rpc-user
                key: user

          - name: RPCPASS
            valueFrom:
              secretKeyRef:
                name: btcd-rpc-user
                key: password

        ports:
          - containerPort: 9735 # peer

        volumeMounts:
          - name: rpc
            mountPath: /rpc
            readOnly: true

          - name: lnd
            mountPath: /root/.lnd

          - name: lnd-rpc-cert
            mountPath: /lnd_rpc_cert
            readOnly: true

      volumes:
        - name: rpc
          secret:
            secretName: btcd-rpc

        - name: lnd
          gcePersistentDisk:
            pdName: lnd

        - name: lnd-rpc-cert
          secret:
            secretName: lnd-rpc-cert
