apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: gcr.io/uiu-server/pika-web
        imagePullPolicy: "Always"

        resources:
          requests:
            cpu: 50m

        env:
          - name: RAILS_ENV
            value: production

          - name: RAILS_LOG_TO_STDOUT
            value: "1"

          - name: LND_RPC_CERT
            value: /rpc/rpc.cert

          - name: LND_MACAROON
            value: /lnd/admin.macaroon

        ports:
          - containerPort: 3000

        volumeMounts:
          - name: rpc
            mountPath: /rpc
            readOnly: true

          - name: lnd
            mountPath: /lnd
            readOnly: true

      volumes:
        - name: rpc
          secret:
            secretName: btcd-rpc

        - name: lnd
          secret:
            secretName: lnd-rpc
