kind: Service
apiVersion: v1
metadata:
  name: web
  labels:
    app: web
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - name: rails
    protocol: TCP
    port: 80
    targetPort: 3000
