apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: gcr.io/uiu-server/pika-web
        imagePullPolicy: "Always"

        resources:
          requests:
            cpu: 50m

        env:
          - name: RAILS_ENV
            value: production

          - name: RAILS_LOG_TO_STDOUT
            value: "1"

          - name: LND_RPC_CERT
            value: /lnd_rpc_cert/tls.cert

          - name: LND_MACAROON
            value: /lnd/admin.macaroon

          - name: DATABASE_HOST
            value: 127.0.0.1

          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username

          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password

          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: web
                key: secret_key_base

        ports:
          - containerPort: 3000

        volumeMounts:
          - name: rpc
            mountPath: /rpc
            readOnly: true

          - name: lnd
            mountPath: /lnd
            readOnly: true

          - name: lnd-rpc-cert
            mountPath: /lnd_rpc_cert
            readOnly: true

      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=uiu-server:asia-northeast1:pika=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]

        resources:
          requests:
            cpu: 0

        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true

      volumes:
        - name: rpc
          secret:
            secretName: btcd-rpc

        - name: lnd
          secret:
            secretName: lnd-rpc

        - name: lnd-rpc-cert
          secret:
            secretName: lnd-rpc-cert

        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
