default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'db' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: "<%= ENV.fetch('DATABASE_USER') { 'postgres' } %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD') { '' } %>"

development:
  <<: *default
  database: pika_development

test:
  <<: *default
  database: pika_test
  host: localhost
  username:
  password:

production:
  <<: *default
  database: pika
